dist: trusty
sudo: false
language: cpp
compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
    - sourceline: 'ppa:sfouladi/protobuf-backports'
    packages:
    - cmake
    - cmake-data
    - protobuf-compiler
    - libprotobuf-dev

script:
  - mkdir build
  - cd build
  - cmake -DBUILD_TESTS=ON .. && make
  - ctest
